global:
  scrape_interval: 5s        # how often Prometheus scrapes targets
  evaluation_interval: 5s    # how often it evaluates rules (none here, but fine)

scrape_configs:
  - job_name: "petcare"
    metrics_path: /metrics   # your Flask /metrics endpoint
    static_configs:
      - targets:
          - "host.docker.internal:5000"
        labels:
          service: "petcare"
          env: "dev"